"""add whatsapp_numbers table

Revision ID: 96f9d757f162
Revises: afb6cea85469
Create Date: 2026-05-15 20:54:01.245625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f9d757f162'
down_revision: Union[str, Sequence[str], None] = 'afb6cea85469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_numbers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('instance_name', sa.String(length=80), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created', 'connecting', 'connected', 'disconnected', 'failed')", name='ck_whatsapp_numbers_status'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_numbers_instance_name'), 'whatsapp_numbers', ['instance_name'], unique=True)
    op.create_index(op.f('ix_whatsapp_numbers_organization_id'), 'whatsapp_numbers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_status'), 'whatsapp_numbers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_numbers_status'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_organization_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_instance_name'), table_name='whatsapp_numbers')
    op.drop_table('whatsapp_numbers')
    # ### end Alembic commands ###
