"""phase 4: conversations, messages, webhook config on numbers

Revision ID: fb69f304e0b7
Revises: 96f9d757f162
Create Date: 2026-05-15 21:10:52.659111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb69f304e0b7'
down_revision: Union[str, Sequence[str], None] = '96f9d757f162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=False),
    sa.Column('remote_jid', sa.String(length=120), nullable=False),
    sa.Column('remote_phone', sa.String(length=40), nullable=True),
    sa.Column('remote_name', sa.String(length=200), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number_id', 'remote_jid', name='uq_conversations_number_remote')
    )
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_remote_jid'), 'conversations', ['remote_jid'], unique=False)
    op.create_index(op.f('ix_conversations_whatsapp_number_id'), 'conversations', ['whatsapp_number_id'], unique=False)
    op.create_table('messages',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('evolution_message_id', sa.String(length=120), nullable=False),
    sa.Column('from_jid', sa.String(length=120), nullable=False),
    sa.Column('to_jid', sa.String(length=120), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type IN ('text', 'image', 'audio', 'video', 'document', 'sticker', 'location', 'contact', 'reaction', 'unknown')", name='ck_messages_content_type'),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name='ck_messages_direction'),
    sa.CheckConstraint("status IN ('pending', 'sent', 'delivered', 'read', 'failed')", name='ck_messages_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number_id', 'evolution_message_id', name='uq_messages_number_evolution_id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_whatsapp_number_id'), 'messages', ['whatsapp_number_id'], unique=False)
    op.add_column('whatsapp_numbers', sa.Column('webhook_url', sa.String(length=500), nullable=True))
    op.add_column('whatsapp_numbers', sa.Column('webhook_secret', sa.String(length=128), nullable=True))
    op.add_column('whatsapp_numbers', sa.Column('webhook_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'whatsapp_numbers',
        sa.Column(
            'webhook_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_numbers', 'webhook_active')
    op.drop_column('whatsapp_numbers', 'webhook_events')
    op.drop_column('whatsapp_numbers', 'webhook_secret')
    op.drop_column('whatsapp_numbers', 'webhook_url')
    op.drop_index(op.f('ix_messages_whatsapp_number_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_whatsapp_number_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_remote_jid'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
